import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Card, { CardContent } from '../src/components/Card/Card'
import styles from '../styles/Home.module.css'
import { getPageData } from '../pages/api/page/data'
import { PageContents } from './_app'
import SlideFade from '../src/animations/SlideFade'
import Link from 'next/link'

type HomeContents = {
  cards: CardContent[]
}

const Home = ({ pageData }: { pageData: PageContents<HomeContents> }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SlideFade>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.ts!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.tsx</code>
          </p>

          <div className={styles.grid}>
            {pageData?.contents?.cards && pageData.contents.cards.map((card, i) => (
              <Card key={i}>
                <a href={card.link}>
                  <h2>{card.title}</h2>
                  <p>{card.description}</p>
                </a>
              </Card>
            ))}
            <Card key={'customCard'}>
              <Link href={'/demo/form/page0'}>
                <a>
                  page0
                </a>
              </Link>
            </Card>
          </div>
        </SlideFade>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

// statically get page data from our API
export const getStaticProps: GetStaticProps = async (context) => {
  // running on the server, we can directly call `getPageData`
  const pageDataString = await getPageData({ for: 'home' })
  const pageData: PageContents<HomeContents> = JSON.parse(pageDataString)

  return {
    props: {
      pageData
    }
  }
}